#!/bin/bash

[[ $# -eq 0 ]] || exit
read -erp "enter a directory path: " DIR
[[ -d $DIR ]] || exit 1

EXT='.txt'
fileList=$(/usr/bin/find $DIR -maxdepth 1 -type f -name "*.txt" -exec basename -s $EXT {} \; | sort)

function main_menu {
PS3="Enter a number next to a video, or press '1' to quit: "
COLUMNS=80
select fileName in quit $fileList; do
        case $fileName in
	quit) exit;;
	$fileName) rip-play ${DIR}${fileName}${EXT} null 2>;;
	*) echo “Invalid Selection, enter a number”;;
esac
break
done
}
while true; do main_menu; done