#!/bin/bash

[[ $# -eq 0 ]] || exit; read -erp "enter a directory path: " DIR
[ -d $DIR ] && /usr/bin/find $DIR -maxdepth 1 -name '*.txt' -type f -print0 | /usr/bin/xargs -i -0 rip-record '{}' || echo no directory