#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ -f "$1" ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"
printf "%s\n" "$VIDEOURL" | while read url; do source "$USERPROFILE/git/kodi-playercorefactory/bash-scripts-windows/video-regex.sh"

case "$url" in
	$VIDEOFILE) mpv --vo=direct3d "$VIDEOFILE";;
	$M3U8) mpv --vo=direct3d "$M3U8";;
	$M3U8TOKEN) mpv --vo=direct3d "$M3U8TOKEN";;
	$XFORWARD) mpv --vo=direct3d --http-header-fields="X-Forwarded-For: $XFORWARDIP" "$M3U8";;
	$USEREF) mpv --vo=direct3d --user-agent="$USERAGENT" --referrer="$REFERER" "$VIDEOFILE";;
	$M3U8USERAGENT) mpv --vo=direct3d --user-agent="$USERAGENT" "$M3U8";;
	$M3U8USERAGENT2) mpv --vo=direct3d --user-agent="$USERAGENT" "$M3U8UAG";;
	$M3U8UAGENTREFERER) mpv --vo=direct3d --user-agent="$USERAGENT" --referrer="$REFERER" "$M3U8";;
	$REFUSERAGENT) mpv --vo=direct3d --user-agent="$USERAGENT" --referrer="$REFERER" "$VIDEOFILE";;
	$RTMP) rtmpdump -q -i "$RTMP" | mpv --vo=direct3d -;;
	$HTTP) mpv --vo=direct3d "$HTTP";;
	*) mpv --vo=direct3d "$VIDEOURL";;
esac 
done
