#!/bin/bash

#+==========================================================+#
# rip-ssh - execute ffmpeg commands based on matching url    #
#+==========================================================+#

# diagram of how the script works
# [rip-ssh] > [ssh server] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ssh]

#+=========================================================+#
# exit status and error codes											#
#+=========================================================+#

SUCCESS=0		# success exit code
E_NOARGS=65		# no arguments passed to script
E_WRONGARGS=66 # wrong number of arguments passed to script
E_NOMATCH=67	# url not matched by regular expression

#+=========================================================+#
# display script usage when script is run with no arguments #
# + or when invalid input is entered by the user				#
#+=========================================================+#

script_usage="Usage: $(basename "$0") [ssh server] [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"

#+=========================================================+#
# validate user input for first, second and third arguments #
# + passed to script	by matching with regular expressions	#
#+=========================================================+#

sshserver="$1" 												 # ssh server
first_arg_validated="^[a-zA-Z0-9:0-9./@-]*"         # validate ssh server address
second_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
third_arg_validated="^-t$"									 # matches: -t
fourth_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00

#+========================================================+#
# second and third arguments passed to script are used	  #
# + to specify a recording duration								  #
#+========================================================+#

tflag="$3" 		# third argument should be: -t
duration="$4"	# fourth argument should be in this format: 00:00:00

#+========================================================+#
# check if second argument is a url in a text file 		  #
# + or a url on the command line									  #
#+========================================================+#

if [[ "$2" =~ \.txt$ ]]; then # - text file passed as second argument to script
	videourl=$(cat "$2")  		# + cat the text file to extract the url
else
	videourl="$2"					# url is on the command line
fi

#+========================================================+#
# check if 2 or 4 arguments are passed to script			  #
# + and validate user input										  #
#+========================================================+#

if [[ $# -eq 2 ]]; then										    # - two argument are passed to the script
	if ! [[ $videourl =~ $second_arg_validated ]]; then # + if videourl doesnt match validation regular expression
		printf "%s\n" "'$videourl' invalid input"			 # + display invalid user input with error message
		printf "%s\n" "$script_usage"							 # + display script usage
		exit "$E_NOMATCH"											 # + exit with E_NOMATCH error code
	fi
elif [[ $# -eq 4 ]]; then										 # - three arguments are passed to the script, validate user input
	if ! [[ $sshserver =~ $first_arg_validated && $videourl =~ $second_arg_validated && $tflag =~ $third_arg_validated && $duration =~ $fourth_arg_validated ]]; then
		printf "%s\n" "'$1 $2 $3 $4' invalid input" 		 # + display invalid user input with error message
		printf "%s\n" "$script_usage"							 # + display script usage
		exit "$E_NOMATCH"											 # + exit with E_NOMATCH error code
	fi
else [[ $# -eq 0 ]]												 # - no arguments are passed to the script
   printf "%s\n" "$script_usage"								 # + display script usage
	exit "$E_NOARGS" 												# + exit with E_NOARGS error code
fi

#+========================================================+#
# enable shell globbing for pattern matching					  #
#+========================================================+#

shopt -s extglob 

#+========================================================+#
# video recording file path										  #
#+========================================================+#

recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 

#+========================================================+#
# case statement switch on pattern match						  #
#+========================================================+#

videofile="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.@(mkv|mp4|avi|flv)"
m3u8="@(http|https)://[a-zA-Z0-9:0-9./?=_,@\&%-]*\.m3u8"
m3u8token="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.m3u8\?token=[a-zA-Z0-9\&=]*"
xforward="@(http|https)://[a-zA-Z0-9./?=_@%-]*\.m3u8\|X-Forwarded-For=+([0-9])\.+([0-9])\.+([0-9])\.+([0-9])"
useref="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.@(mkv|mp4|avi|flv)\|[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+-]*\&[rR]eferer=@(http|https)@(://|%3A%2F%2F)[a-zA-Z%0-9./?=_-]*"
m3u8useragent="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.m3u8?([a-zA-Z0-9?\&=%*])*\|[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+_-]*[\&]"
m3u8uagentreferer="@(http|https)://[a-zA-Z0-9:0-9./?=_\&@%-]*\.m3u8\|[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;\&@%+-]*\&[rR]eferer=@(http|https)@(://|%3A%2F%2F)[a-zA-Z%0-9./?=_-]*"
cookiem3u8="@(http|https)://[a-zA-Z0-9:0-9./?=_,@\&%-]*\.m3u8\?nltid=[a-zA-Z0-9\&%_*=]*"
refuseragent="@(http|https)://[a-zA-Z0-9:0-9./?=_-]*\|[rR]eferer=@(http|https)@(://|%3A%2F%2F)[a-zA-Z%0-9./?=_-]*\&[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+-]*"
m3u8refuseragent="@(http|https)://[a-zA-Z0-9:0-9./?=_-]*\.m3u8\|[rR]eferer=@(http|https)@(://|%3A%2F%2F)[a-zA-Z%0-9./?=_-]*\&[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+-]*"
http="@(http|https)://[a-zA-Z0-9:0-9/.\&;,~*?%@_=-]*"
rtmp="@(rtmp|rtmpe)://[a-zA-Z0-9[:blank:]#%@!()_=:-/.\&;,~*?]*"
cookiem3u8uagent="@(http|https)://[a-zA-Z0-9:0-9./?=_,@\&%-]*\.m3u8\|[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+_-]*\&Cookie=mediaAuth=[a-zA-Z0-9]*"

#+========================================================+#
# grep inside url to extract strings							  #
#+========================================================+#

videofile_grep=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.(mkv|mp4|avi|flv)')
m3u8_grep=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_,@&%-]*\.m3u8?([a-zA-Z0-9?&=%*]*[^|])')
useragent=$(printf "%s" "$videourl" | grep -Eo 'u?User-a?Agent=[a-zA-Z0-9/.()[:blank:],:;%+_-]*[^&]')
useragent2=$(printf "%s" "$videourl" | grep -Eo 'u?User-a?Agent=[a-zA-Z0-9/.()[:blank:],:;%+_-]*[^&]' | sed 's/[uU]ser-[aA]gent=//g')
referer=$(printf "%s" "$videourl" | grep -Eo 'r?Referer=(http|https)(://|%3A%2F%2F)[a-zA-Z%0-9./?=_-]*'| sed 's/[rR]eferer=//')
xforwardip=$(printf "%s" "$videourl" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
cookieurl=$(printf "%s" "$videourl" | grep -Eo 'nltid=[a-zA-Z0-9&%_*=]*')
cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*[^/]' | sed 's/^http\(\|s\):\/\///g')


#+========================================================+#
# case statement with regular expression 						  #
# + to execute ffmpeg commands based on matching url		  #
#+========================================================+#

case "$videourl" in
	$videofile)         # video file
		printf "%s\n" 'url matches: $videofile bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -i' "$videourl" \
		'-c:v copy -c:a copy' $tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$m3u8)              # m3u8 playlist
		printf "%s\n" 'url matches: $m3u8 bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -i' "$videourl" \
		'-c:v copy -bsf:a aac_adtstoasc' $tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$m3u8token)         # m3u8 playlist + token
		printf "%s\n" 'url matches: $m3u8token bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel panic -i' "$videourl" \
		'-bsf:v mpeg4_unpack_bframes -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$xforward)          # xforward
		printf "%s\n" 'url matches: $xforward bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s '%s' %s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -headers' \
		'X-Forwarded-For: '"$xforwardip"''$'\r\n' \
		'-i' "$m3u8_grep" \
		'-c:v copy -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$useref)            # useragent referer
		printf "%s\n" 'url matches: $useref bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s %s %s %s %s %s %s %s %s\n" \
		'ffmpeg -hide_banner -user-agent' "$useragent" \
		'-headers' \
		'Referer: '"$referer"''$'\r\n' \
		'-i' "$videofile_grep" '-c:v copy -c:a copy' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$m3u8useragent)     # m3u8 user agent 
		printf "%s\n" 'url matches: $m3u8useragent bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s %s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel error -user-agent' \
		"$useragent" '-i' "$m3u8_grep" \
		'-c:v copy -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$m3u8uagentreferer) # m3u8 useragent referer
		printf "%s\n" 'url matches: $m3u8uagentreferer bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s %s '%s' %s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel error -user-agent' \
		"$useragent" \
		'-headers' \
		'Referer: '"$referer"''$'\r\n' \
		'-i' "$m3u8_grep" \
		'-c:v copy -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$m3u8refuseragent)  # m3u8 referer user agent
		printf "%s\n" 'url matches: $m3u8refuseragent bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s '%s' %s %s %s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel error' \
		'-headers' \
		'Referer: '"$referer"''$'\r\n' \
		'-user-agent' "$useragent" \
		'-i' "$m3u8_grep" \
		'-c:v copy -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$refuseragent)      # referer user agent
		printf "%s\n" 'url matches: $refuseragent bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s '%s' %s %s %s '%s' %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel error' \
		'-headers' \
		'Referer: '"$referer"''$'\r\n' \
		'-user-agent' "$useragent" \
		'-i' "$videofile_grep" \
		'-c:v copy -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$rtmp)              # rtmp
		printf "%s\n" 'url matches: $rtmp bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s '%s' %s %s %s %s %s\n" \
		'rtmpdump -q -i' "$rtmp" \
		'| ffmpeg -hide_banner -i -' \
		'-c:v copy -c:a copy' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$cookiem3u8)        # cookie m3u8
		printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s '%s' %s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel panic' \
		'-cookies' \
		"$cookieurl; path=/; $cookiedomain;" \
		'-i' "$videourl" \
		'-c:v copy -bsf:a aac_adtstoasc' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$cookiem3u8uagent)  # cookie m3u8 useragent
		printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s %s '%s' %s '%s' %s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -loglevel panic' \
		'-user-agent' "$useragent2" \
		'-cookies' "$cookiemedia; path=/; $cookiedomain;" \
		'-i' "$m3u8_grep" \
		'-c:v copy -c:a copy' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	$http)              # http
		printf "%s\n" 'url matches: $http bash pattern'
		printf "%s\n" "Recording: a'$videourl'"
		printf "%s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -i' "$videourl" \
		'-c:v copy -c:a copy' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
	*) 		           # wildcard
		printf "%s\n" 'url matches: * bash pattern'
		printf "%s\n" "Recording: '$videourl'"
		printf "%s '%s' %s %s %s %s\n" \
		'ffmpeg -hide_banner -i' "$videourl" \
		'-c:v copy -c:a copy' \
		$tflag $duration \
		"$recordingfile" \
		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
esac 

#+========================================================+#
# turn off shell globbing											  #
#+========================================================+#

shopt -u extglob 

#+========================================================+#
# exit status SUCCESS if script runs without errors		  #
#+========================================================+#

exit "$SUCCESS"
