#!/bin/bash

[[ $# -eq 0 ]] || exit
read -erp "enter a directory path to txt files: " DIR
[ -d $DIR ] && /usr/bin/find $DIR -maxdepth 1 -name '*.txt' -type f \
| while read file
do
grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.txt' "$file" >> iptv.txt
done || echo no directory found
