#!/bin/bash

[[ $# -eq 0 ]] || exit
read -erp "enter a path to a directory or xml txt file: " DIR
[[ -d $DIR || -f $DIR ]] && /usr/bin/find $DIR -maxdepth 1 -regex ".*\.\(xml\|txt\)" -type f \
| while read file
do 
awk -F "[><]" '/title/{print $3} /name/{print $3} /link/{print $3}' "$file" \
| sed 's/^[^(http)]/#&/' >> xml-links.txt
done || echo no directory or file found