#!/bin/bash

# ffmpeg multicast stream

if [[ $# < 1 ]]
	then
		printf "%b" "error not enough aruments passed to the script" '\n'
		exit 1 # exit with non zero		
elif [[ $# > 3 ]]
	 then
		printf "%b" "too many aruments passed to the script" '\n'
		exit 2 # exit with non zero
else

VIDEOURL=`cat "$1"`
TFLAG="$2"
DURATION="$3"

echo $VIDEOURL |
while read url
do
# http link to m4v, mp4, avi, flv
VIDEOFILE=`echo "$VIDEOURL" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_@%-]*\.(mkv|mp4|avi|flv)'`

# http link to m3u8 file
M3U8=`echo "$VIDEOURL" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_@%-]*\.(m3u8)'`

# http link to m3u8 with x forward header
XFORWARD=`echo "$VIDEOURL" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_@%-]*\.(m3u8)\|X-Forwarded-For=[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
XFORWARDIP=`echo "$XFORWARD" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`

# http link to m4v, mp4, avi, flv with user agent and referer http header
USEREF=`echo "$VIDEOURL" | grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_-]*\.(mkv|mp4|m3u8|avi|flv)\|User-Agent=[a-zA-Z]*/[0-9]{1,1}\.[0-9]{1,1}(.*)\&Referer=(http|https)://[a-zA-Z0-9./?=_-]*(/|\.html)'`
USERAGENT=`echo "$USEREF" | grep -Eo 'User-Agent=[a-zA-Z]*/[0-9]{1,1}\.[0-9]{1,1}(.[^&]*)'`
REFERER=`echo "$USEREF" | grep -Eo 'Referer=(http|https)://[a-zA-Z0-9./?=_-]*(/|\.html)' | sed 's/Referer=//'`

# http link to m3u8 with x forward header and user agent
M3U8USERAGENT=`echo "$VIDEOURL" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_@%-]*\.(m3u8)\|user-agent=[a-zA-Z]*'`
M3U8UAG=`echo "$M3U8USERAGENT" | grep -Eo 'user-agent=[a-zA-Z]*' | sed 's/user-agent=//'`
M3U8UAGM3U8=`echo "$M3U8USERAGENT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_@%-]*\.(m3u8)'`

case "$url" in
"$VIDEOFILE")
	/usr/bin/ffmpeg -hide_banner -re -i "$VIDEOFILE" \
	-c:v libx265 -preset ultrafast -tune zero-latency \
	-x265-params crf=28 \
	-c:a aac -strict experimental -b:a 192k \
	${TFLAG} ${DURATION} \
	-loglevel error \
	-maxrate 4000k -bufsize 4000k \
	-f mpegts udp://239.253.253.4:1234?pkt_size=1316
	;;
"$M3U8")
	/usr/bin/ffmpeg -hide_banner -i "$M3U8" \
	-c:v copy -c:a copy \
	${TFLAG} ${DURATION} \
	-loglevel error \
	-f mpegts udp://239.253.253.4:1234?pkt_size=1316
	;;
"$XFORWARD")
	/usr/bin/ffmpeg -hide_banner -headers 'X-Forwarded-For: '"$XFORWARDIP"''$'\r\n' -i "$M3U8" \
	-c:v copy -c:a copy \
	${TFLAG} ${DURATION} \
	-loglevel error \
	-f mpegts udp://239.253.253.4:1234?pkt_size=1316
	;;
"$USEREF")
	/usr/bin/ffmpeg -hide_banner -re -i  "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' -i "$URL" \
	-c:v libx265 -preset ultrafast -tune zero-latency \
	-x265-params crf=28 \
	-c:a aac -strict experimental -b:a 192k \
	${TFLAG} ${DURATION} \
	-loglevel error \
	-maxrate 4000k -bufsize 4000k \
	-f mpegts udp://239.253.253.4:1234?pkt_size=1316
	;;
"$M3U8USERAGENT")
	/usr/bin/ffmpeg -hide_banner -loglevel error -user-agent "$M3U8UAG" -i "$M3U8UAGM3U8" \
	-c:v copy -c:a copy \
	${TFLAG} ${DURATION} \
	-loglevel error \
	-f mpegts udp://239.253.253.4:1234?pkt_size=1316
	;;
*)
	/usr/bin/ffmpeg -hide_banner -re -i "$VIDEOURL" \
	-c:v libx265 -preset ultrafast -tune zero-latency \
	-x265-params crf=28 \
	-c:a aac -strict experimental -b:a 192k \
	${TFLAG} ${DURATION} \
	-loglevel error \
	-maxrate 4000k -bufsize 4000k \
	-f mpegts udp://239.253.253.4:1234?pkt_size=1316
	;;
esac
done
fi