#!/bin/bash

[[ $# -eq 0 ]] && CURLINE=0 || exit
read -erp "enter the path to your m3u file: " FILE
[[ -f "$FILE" ]] && find "$FILE" -maxdepth 1 -name '*.m3u' -type f \
| while read line; do
	PLX=`printf '%s' "$FILE" | sed -e 's/.m3u/.plx/g'`
	PTITLE=`printf '%s' "$FILE" | sed -e 's/.m3u//'`
	VER='version=1'
	BGROUND='background='
	TITLE="title=$PTITLE"
	NAME=`printf '%s\n' "$line" | grep -Eo '\#EXTINF:0,[a-zA-Z0-9+&;[:blank:]]*' | sed 's/#EXTINF:0,/name=/g'`
	PLUGIN=`printf '%s\n' "$line" | grep -Eo 'plugin://[a-zA-Z0-9./_?&%+=;]*[^(&quot;)]'`
	[[ "$CURLINE" -eq 0 ]] && printf '%s\n%s\n%s\n%s\n' "$VER" "$BGROUND" "$TITLE" '#' > "$PLX"
	[[ -n "$NAME" ]] && printf '%s\n' 'type=video' >> "$PLX"
	printf '%s\n' "$line" | grep -Eo '\#EXTINF:0,[a-zA-Z0-9+&;[:blank:]]*' | sed 's/#EXTINF:0,/name=/g' >> "$PLX"
	printf '%s\n' "$line" | grep -Eo 'iconimage=[a-zA-Z0-9%._]*[^(&description)]' | sed 's/iconimage/thumb/' | sed 's/%2F/\//g' >> "$PLX" 
	printf '%s\n' "$line" | grep -Eo 'plugin://[a-zA-Z0-9./_?&%+=;]*[^(&quot;)]' | sed 's/plugin/URL=&/' >> "$PLX" 
	[[ -n "$PLUGIN" ]] && printf '%s\n' '#' >> "$PLX"
        ((CURLINE++))
done < "$FILE"