#!/bin/bash

[[ $# -eq 0 ]] && CURLINE=0 || exit
read -erp "enter the path to your m3u file: " FILE
[[ -f "$FILE" ]] && find "$FILE" -maxdepth 1 -name '*.m3u' -type f \
| while read line; do
	VER='version=1'
	BGROUND='background='
	TITLE='title='
	NAME=`printf '%s\n' "$line" | grep -Eo '\#EXTINF:0,[a-zA-Z0-9+&;[:blank:]]*' | sed 's/#EXTINF:0,/name=/g'`
	PLUGIN=`printf '%s\n' "$line" | grep -Eo 'plugin://[a-zA-Z0-9./_?&%+=;]*[^(&quot;)]'`
	[[ "$CURLINE" -eq 0 ]] && printf '%s\n%s\n%s\n%s\n' "$VER" "$BGROUND" "$TITLE" '#' > iptv-links.plx
	[[ -n "$NAME" ]] && printf '%s\n' 'type=video' >> iptv-links.plx
	printf '%s\n' "$line" | grep -Eo '\#EXTINF:0,[a-zA-Z0-9+&;[:blank:]]*' | sed 's/#EXTINF:0,/name=/g' >> iptv-links.plx
	printf '%s\n' "$line" | grep -Eo 'iconimage=[a-zA-Z0-9%._]*[^(&description)]' | sed 's/iconimage/thumb/' | sed 's/%2F/\//g' >> iptv-links.plx
	printf '%s\n' "$line" | grep -Eo 'plugin://[a-zA-Z0-9./_?&%+=;]*[^(&quot;)]' | sed 's/plugin/URL=&/' >> iptv-links.plx
	[[ -n "$PLUGIN" ]] && printf '%s\n' '#' >> iptv-links.plx
        ((CURLINE++))
done < "$FILE"