#!/bin/bash

[[ $# -eq 0 ]] && CURLINE=0 || exit
read -erp "enter the path to your plx file: " FILE
[[ -f "$FILE" ]] && find "$FILE" -maxdepth 1 -name '*.plx' -type f \
| while read line; do	
	NAME=`printf '%s' "$line" | grep -Eo 'name=[a-zA-Z0-9&;[:blank:]]*' | sed 's/name=//'`
	URL=`printf '%s' "$line" | grep -Eo 'plugin://[a-zA-Z0-9./_?&%+=;]*[^(&quot;)]'`
	OUTNAME='custom-addons.ini'
	[[ -n "$NAME" ]] && printf '%s%s' "$NAME" "=" >> "$OUTNAME" 
	[[ -n "$URL" ]] && printf '%s\n\n' "$URL" >> "$OUTNAME"
        ((CURLINE++))
done < "$FILE"