#!/bin/bash

[[ $# -eq 0 ]] || exit
read -erp "enter a directory path to plx files: " DIR
[ -d $DIR ] && find $DIR -maxdepth 1 -name '*.plx' -type f \
| while read file
do
awk '/name/{print $1} /URL/{print $1}' "$file" \
| sed 's/^[(URL|name)=]*//' | sed 's/^[^(http)]/#&/' >> plx-links.txt
done || echo no directory found