#!/bin/bash

[[ $# -eq 0 ]] || exit
EXT='.txt'
read -erp "enter a directory path: " DIR
[ -d $DIR ] && fileList=$(find $DIR -maxdepth 1 -type f -name "*.txt" -exec basename -s $EXT {} \;)

function main_menu {
PS3="Enter a number next to a video, or press '1' to quit: "
select fileName in quit $fileList; do
        case $fileName in
	quit ) exit;;
	$fileName ) echo rip-play ${DIR}${fileName}${EXT};;
	* ) echo “Invalid Selection, enter a number” ;;
esac
break
done
}
while true; do main_menu; done
