#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ -f "$1" ]] && VIDEOURL=`cat "$1"` || VIDEOURL="$1"
echo $VIDEOURL | while read url; do source video-regex.sh

case "$url" in
	"$VIDEOFILE") vlc "$VIDEOFILE";;
	"$M3U8") vlc "$M3U8";;
	"$M3U8TOKEN") ffmpeg -i "$M3U8TOKEN" | vlc fd://0;;
	"$XFORWARD") ffmpeg -headers 'X-Forwarded-For: '"$XFORWARDIP"''$'\r\n' -i "$M3U8" | vlc fd://0;;
	"$USEREF") ffmpeg -user-agent "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' -i "$VIDEOFILE" | vlc fd://0;;
	"$M3U8USERAGENT") ffmpeg -user-agent "$USERAGENT" -i "$M3U8UAG" | vlc fd://0;;
	"$GVID") vlc "$GVID";;
	"$M3U8UAGENTREFERER") ffmpeg -user-agent "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' -i "$M3U8UAGNTREF" | vlc fd://0;;
	"$REFUSERAGENT") ffmpeg -headers 'Referer: '"$REFERER"''$'\r\n' -user-agent "$USERAGENT" -i "$VIDEOFILE" | vlc fd://0;;
	"$BEEB") vlc "$BEEB";;
	"$RTMP") rtmpdump -i "$RTMP" | vlc fd://0;;
	*) vlc "$VIDEOURL";;
esac 
done