#!/bin/bash

# ffprobe analyse video url 

if [[ $# < 1 ]]
	then
		printf "%b" "error not enough aruments passed to the script" '\n'
		exit 1 # exit with non zero		
elif [[ $# > 1 ]]
	 then
		printf "%b" "too many aruments passed to the script" '\n'
		exit 2 # exit with non zero
else

VIDEOURL=`cat "$1"`

echo $VIDEOURL |
while read url
do
source video-regex.sh

case "$url" in
	"$VIDEOFILE")
	ffprobe -v error -hide_banner -show_entries \
	format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rate,width,height -of csv \	
	-i "$VIDEOFILE" \
	| tee "$HOME/Desktop/video-stats-$(date +"%m-%d-%y-%H-%M").txt"
	;;
	"$M3U8")
	ffprobe -v error -hide_banner -show_entries \
	format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rate,width,height -of csv \
	-i "$M3U8" \
	| tee "$HOME/Desktop/video-stats-$(date +"%m-%d-%y-%H-%M").txt"
	;;
	"$XFORWARD")
	ffprobe -v error -hide_banner -show_entries \
	format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rate,width,height -of csv \
	-headers 'X-Forwarded-For: '"$XFORWARDIP"''$'\r\n' -i "$M3U8" \
	| tee "$HOME/Desktop/video-stats-$(date +"%m-%d-%y-%H-%M").txt"
	;;
	"$USEREF")
	ffprobe -v error -hide_banner -show_entries \
	format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rate,width,height -of csv \
	-user-agent "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' -i "$URL" \
	| tee "$HOME/Desktop/video-stats-$(date +"%m-%d-%y-%H-%M").txt"
	;;
	"$M3U8USERAGENT")
	ffprobe -v error -hide_banner -show_entries \
	format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rate,width,height -of csv \
	-user-agent "$M3U8UAG" -i "$M3U8UAGM3U8" \
	| tee "$HOME/Desktop/video-stats-$(date +"%m-%d-%y-%H-%M").txt"
	;;
	*)
	ffprobe -v error -hide_banner -show_entries \
	format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rate,width,height -of csv \
	-i "$VIDEOURL" \
	| tee "$HOME/Desktop/video-stats-$(date +"%m-%d-%y-%H-%M").txt"
	;;
esac
done
fi