#!/bin/bash

#+=================================================================+#
# rip-watch - monitor ffmpeg processes                              #
#+=================================================================+#

SUCCESS=0      # success exit code
E_WRONGARGS=65 # wrong number of arguments passed to script

#+=================================================================+#
# display script usage when script is run wrong number of arguments #
#+=================================================================+#

if [[ $# -ne 0 ]]; then
    script_usage="Usage: $(basename "$0")"
    printf "%s\n" "$script_usage"
    exit "$E_WRONGARGS"
fi

#+=================================================================+#
# monitor ffmpeg proceses and show start time and elapsed time      # 
#+=================================================================+#

watch -n 1 "ps -C ffmpeg -o pid,comm,start,etime"

exit "$SUCCESS"
