#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ -f "$1" ]] && VIDEOURL=`cat "$1"` || VIDEOURL="$1"
source kodi-external-player-ip.sh
curl --data-binary \
"{ \"jsonrpc\": \"2.0\", \"method\": \"Player.Open\", \"params\": { \"item\": { \"file\": \"$VIDEOURL\" } }, \"id\": 1 }" \
-H 'content-type: application/json;' http://"$IPADDR":8080/jsonrpc