#!/bin/bash

# rip batch recording

if [[ $# > 0 ]]
	then
		printf "%b" "too many aruments passed to the script" '\n'
		exit 1 # exit with non zero
else

read -erp "enter a directory path: " DIR

if [ -d $DIR ]
  then
    find $DIR -maxdepth 1 -name '*.txt' -type f -print0 | xargs -i -0 rip-record '{}' -t 00:02:00
  else
    echo directory doesnt exist
fi

fi