#!/bin/bash

# rip-record - execute ffmpeg commands based on matching url
#===========================================================

# check if 1 or 3 arguments are passed to script
[[ $# -eq 1 ]] || [[ $# -eq 3 ]] || exit 
[[ "$1" =~ \.txt$ ]] && videourl=$(<"$1") || videourl="$1" 

# enable shell globbing for pattern matching
shopt -s extglob 

# ffmpeg duration 2nd and 3rd arguments passed to script
tflag="$2"
duration="$3" 

# video recording file path
recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 

# case statement switch on pattern match
videofile="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.@(mkv|mp4|avi|flv)" # video file
m3u8="@(http|https)://[a-zA-Z0-9:0-9./?=_,@\&%-]*\.m3u8" # m3u8 playlist
m3u8token="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.m3u8\?token=[a-zA-Z0-9\&=]*" # m3u8 playlist + token
xforward="@(http|https)://[a-zA-Z0-9./?=_@%-]*\.m3u8\|X-Forwarded-For=+([0-9])\.+([0-9])\.+([0-9])\.+([0-9])" # x-forward
useref="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.@(mkv|mp4|avi|flv)\|[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+-]*\&[rR]eferer=@(http|https)@(://|%3A%2F%2F)[a-zA-Z%0-9./?=_-]*" # user agent + referer

# pattern match inside command - delete match we want the reminder
xforwardip="${videourl##*X-Forwarded-For=}" # match from the start
xforwardm3u8="${videourl%%\|X-Forwarded-For=*}" # match from the back
#useragent="${videourl##*[uU]ser-[aA]gent=!([a-zA-Z0-9/.()[:blank:],:;%+-]*)*([^\&])}"
useragent="${videourl##*[uU]ser-[aA]gent=!([a-zA-Z0-9/.()[:blank:],:;%+-]*)}"
referer="${videourl##*[uU]ser-[aA]gent=!([&])[rR]eferer=}"
videofilecase="${videourl%%\|*}" # match from back

# case statement with regular expression to execute ffmpeg commands based on matching url
case "$videourl" in
	$videofile) # video file
		ffmpeg -hide_banner -i "$videourl" -c:v copy -c:a copy "$tflag" "$duration" "$recordingfile";;
	$m3u8)      # m3u8 playlist
		ffmpeg -hide_banner -loglevel error -i "$videourl" \
		-c:v copy -bsf:a aac_adtstoasc "$tflag" "$duration" "$recordingfile";;
	$m3u8token) # m3u8 playlist + token
		ffmpeg -hide_banner -loglevel error -i "$videourl" \
		-bsf:v mpeg4_unpack_bframes -bsf:a aac_adtstoasc "$tflag" "$duration" "$recordingfile";;
	$xforward)  # xforward
		ffmpeg -hide_banner -headers 'X-Forwarded-For: '"$xforwardip"''$'\r\n' -i "$xforwardm3u8" \
		-c:v copy -bsf:a aac_adtstoasc "$tflag" "$duration" "$recordingfile";;
	$useref)    # useragent referer
		echo ffmpeg -hide_banner -user-agent "$useragent" -headers 'Referer: '"$referer"''$'\r\n' \
		-i "$videofilecase" -c:v copy -c:a copy "$tflag" "$duration" "$recordingfile";;
	*) 		   # wildcard
		echo wildcard - ffmpeg -hide_banner -i "$videourl" -c:v copy -c:a copy "$tflag" "$duration" "$recordingfile";; 
esac 

# turn off shell globbing
shopt -u extglob 
