#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ -f "$1" ]] && VIDEOURL=`cat "$1"` || VIDEOURL="$1"
IPADDR=`grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' "kodi-external-player-ip.txt"`
xbmc-send --host="$IPADDR" --port=9777 --action="PlayMedia("$VIDEOURL")"