#!/bin/bash

[[ $# -eq 0 ]] || exit
read -erp "enter a path to a directory or xml file: " DIR
[ -d $DIR ] && find $DIR -maxdepth 1 -name '*.xml' -type f \
|| [ -f $DIR ] && find $DIR -maxdepth 1 -name '*.xml' -type f \
| while read file
do 
awk -F "[><]" '/title/{print $3} /name/{print $3} /link/{print $3}' "$file" \
| sed 's/^[^(http)]/#&/' >> xml-links.txt
done || echo no directory or file found