#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ "$1" =~ \.txt$ ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"
printf "%s\n" "$VIDEOURL" | while read url; do source $HOME/git/kodi-playercorefactory/bash-scripts-macosx/video-regex.sh

case "$url" in
	$VIDEOFILE)
		printf "%s\n" VIDEOFILE;;
	$M3U8)
		printf "%s\n" M3U8;;
	$M3U8TOKEN)
		printf "%s\n" M3U8TOKEN;;
	$XFORWARD)
		printf "%s\n" XFORWARD;;
	$USEREF)
		printf "%s\n" USEREF;;
	$M3U8USERAGENT)
		printf "%s\n" M3U8USERAGENT;;
	$M3U8USERAGENT2)
		printf "%s\n" M3U8USERAGENT2;;
	$M3U8UAGENTREFERER)
		printf "%s\n" M3U8UAGENTREFERER;;
	$REFUSERAGENT)
		printf "%s\n" REFUSERAGENT;;
	$RTMP)
		printf "%s\n" RTMP;;
	$COOKIEM3U8)
		printf "%s\n" COOKIEM3U8;;
	$COOKIEM3U8UAGENT)
		printf "%s\n" COOKIEM3U8UAGENT;;
	$HTTP)
		printf "%s\n" HTTP;;
	*)
		printf "%s\n" WILDCARD;;
esac 
done
