#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ -f "$1" ]] && VIDEOURL=`cat "$1"` || VIDEOURL="$1"
source $HOME/git/kodi-playercorefactory/bash-scripts-macosx/kodi-external-player-ip.sh
python2 $HOME/git/kodi-playercorefactory/bash-scripts-macosx/kodi-send.py --host="$IPADDR" --port=9777 --action="PlayMedia($VIDEOURL,[playoffset=0])"