#!/bin/bash

[[ $# -eq 1 ]] || [[ $# -eq 3 ]] || exit
[[ -f "$1" ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"
TFLAG="$2"; DURATION="$3"
NOTIFY='/Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier'
printf "%s\n" "$VIDEOURL" | while read url; do source $HOME/git/kodi-playercorefactory/bash-scripts-macosx/video-regex.sh

case "$url" in
	$VIDEOFILE)
		$HOME/bin/ffmpeg -hide_banner -i "$VIDEOFILE" \
		-c:v copy -c:a copy ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	$M3U8)
		$HOME/bin/ffmpeg -hide_banner -i "$M3U8" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv" 2>&1 | sed '/\[/d';;
	$M3U8TOKEN)
		$HOME/bin/ffmpeg -hide_banner -loglevel panic -i "$M3U8TOKEN" \
		-bsf:v mpeg4_unpack_bframes -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	$XFORWARD)
		$HOME/bin/ffmpeg -hide_banner -headers 'X-Forwarded-For: '"$XFORWARDIP"''$'\r\n' -i "$M3U8" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	$USEREF)
		$HOME/bin/ffmpeg -hide_banner -user-agent "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' -i "$URL" \
		-c:v copy -c:a copy ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%H-%M-%m-%d-%y").mkv";;
	$M3U8USERAGENT)
		$HOME/bin/ffmpeg -hide_banner -loglevel error -user-agent "$USERAGENT" -i "$M3U8" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%H-%M-%m-%d-%y").mkv";;
	$M3U8USERAGENT2)
		$HOME/bin/ffmpeg -hide_banner -loglevel error -user-agent "$USERAGENT" -i "$M3U8UAG" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%H-%M-%m-%d-%y").mkv";;
	$GVID)
		$HOME/bin/ffmpeg -hide_banner -i "$GVID" \
		-c:v copy -c:a copy ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	$M3U8UAGENTREFERER)
		$HOME/bin/ffmpeg -hide_banner -loglevel error -user-agent "$USERAGENT" \
		-headers 'Referer: '"$REFERER"''$'\r\n' \
		-i "$M3U8UAGNTREF" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%H-%M-%m-%d-%y").mkv";;
	$REFUSERAGENT)
		$HOME/bin/ffmpeg -hide_banner -loglevel error \
		-headers 'Referer: '"$REFERER"''$'\r\n' \
		-user-agent "$USERAGENT" \
		-i "$VIDEOFILE" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%H-%M-%m-%d-%y").mkv";;
	$BEEB)
		$HOME/bin/ffmpeg -hide_banner -i "$BEEB" \
		-c:v copy -c:a copy ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	$RTMP)
		/usr/local/bin/rtmpdump -q -i "$RTMP" | $HOME/bin/ffmpeg -hide_banner -i - \
		-c:v copy -c:a copy ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	$COOKIEM3U8)
		$HOME/bin/ffmpeg -hide_banner -loglevel panic \
		-cookies "$COOKIEURL; path=/; $COOKIEDOMAIN;" \
		-i "$COOKIEM3U8" \
		-c:v copy -bsf:a aac_adtstoasc ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
	*)
		$HOME/bin/ffmpeg -hide_banner -i "$VIDEOURL" \
		-c:v copy -c:a copy ${TFLAG} ${DURATION} \
		"$HOME/Desktop/video-$(date +"%m-%d-%y-%H-%M").mkv";;
esac 
done \
&& type -P "$NOTIFY" &> /dev/null && [[ $? -eq 0 ]] \
&& "$NOTIFY" -sender 'org.xbmc.kodi' -title 'Finished Recording' -message "$VIDEOURL"
