#!/bin/bash

[[ $# -eq 1 ]] || exit
[[ "$1" =~ \.txt$ ]] && VIDEOURL=$(cat "$1") || VIDEOURL="$1"
printf "%s\n" "$VIDEOURL" | while read url; do source $HOME/git/kodi-playercorefactory/bash-scripts-macosx/video-regex.sh

case "$url" in
	$VIDEOFILE) $HOME/bin/$HOME/bin/ffplay -hide_banner -x 640 -y 360 "$VIDEOFILE";;
	$M3U8) $HOME/bin/ffplay -hide_banner -x 640 -y 360 "$M3U8" 2>&1 | sed '/\[/d';;
	$M3U8TOKEN) $HOME/bin/ffplay -hide_banner -x 640 -y 360 "$M3U8TOKEN" 2>&1 | sed '/\[/d';;
	$XFORWARD) $HOME/bin/ffplay -hide_banner -x 640 -y 360 -headers 'X-Forwarded-For: '"$XFORWARDIP"''$'\r\n' "$M3U8";;
	$USEREF) $HOME/bin/ffplay -hide_banner -x 640 -y 360 -user-agent "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' "$VIDEOFILE";;
	$M3U8USERAGENT) $HOME/bin/ffplay -hide_banner -x 640 -y 360 -user-agent "$USERAGENT" "$M3U8";;
	$M3U8USERAGENT2) $HOME/bin/ffplay -hide_banner -x 640 -y 360 -user-agent "$USERAGENT" "$M3U8UAG";;
	$M3U8UAGENTREFERER) $HOME/bin/ffplay -hide_banner -x 640 -y 360 -user-agent "$USERAGENT" -headers 'Referer: '"$REFERER"''$'\r\n' "$M3U8";;
	$REFUSERAGENT) $HOME/bin/ffplay -hide_banner -x 640 -y 360 -headers 'Referer: '"$REFERER"''$'\r\n' -user-agent "$USERAGENT" "$VIDEOFILE";;
	$RTMP) /usr/local/bin/rtmpdump -q -i "$RTMP" | $HOME/bin/ffplay -hide_banner -x 640 -y 360 -;;
	$HTTP) $HOME/bin/ffplay -hide_banner -x 640 -y 360 "$HTTP";;
	*) $HOME/bin/ffplay -hide_banner -x 640 -y 360 "$VIDEOURL";;
esac 
done
