#!/bin/bash

[[ $# -eq 0 ]] && CURLINE=0 || exit
read -erp "enter the path to your text file: " FILE
[[ -f "$FILE" ]] && find "$FILE" -maxdepth 1 -regex ".*\.\(txt\|m3u\)$" -type f \
| while read line; do
	LINK=`echo "$line" | grep -Eo '(http|https|rtmp)://[a-zA-Z0-9:0-9./?=_@&%|()[:blank:],;-]*'`
	[[ -n "$LINK" ]] && echo 'checking:' "$LINK"
	ffprobe -hide_banner "$LINK" 2> /dev/null
	[[ $? -eq 0 ]] && echo "$LINK" >> working.txt
        ((CURLINE++))
done < "$FILE" || echo no file found 